version: "3"

services:
        app:
                build: .
                environment:
                        MONGO_URL: "mongodb://mongo:27017/dbcontainer"
                        RABBIT_MQ_URL: "amqp://guest:guest@rabbit"
                depends_on:
                        - mongo
                        - rabbit
                ports:
                        - 3000:3000
        mongo:
                image: mongo
        rabbit:
                image: rabbitmq:3.6
                restart: "always"
                ports:
                        - 5672:5672
                        - 15672:15672
                environment:
                        RABBITMQ_DEFAULT_PASS: "guest"
                        RABBITMQ_DEFAULT_USER: "guest"
                
                

